framework:
    mailer:
        transports:
            main: 'gmail+smtp://sassi.ali@esprit.tn:certified201@default'
            alternative: 'smtp://5a1eb636198506:800f0ad2529644@sandbox.smtp.mailtrap.io:2525?encryption=tls&auth_mode=login'
            dsn: '%env(MAILER_DSN)%'
        message_bus:  false
